const Cardsdata = [
  {
    login: "CarryMinati",
    id: 0,
    node_id: "MDQ6VXNlcjE=",
    avatar_url:
      "https://static.toiimg.com/photo/msid-82531280/82531280.jpg?247683",
    gravatar_id: "",
    url: "https://api.github.com/users/mojombo",
    html_url: "https://github.com/mojombo",
    followers_url: "https://api.github.com/users/mojombo/followers",
    following_url:
      "https://api.github.com/users/mojombo/following{/other_user}",
    gists_url: "https://api.github.com/users/mojombo/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mojombo/subscriptions",
    organizations_url: "https://api.github.com/users/mojombo/orgs",
    repos_url: "https://api.github.com/users/mojombo/repos",
    events_url: "https://api.github.com/users/mojombo/events{/privacy}",
    received_events_url: "https://api.github.com/users/mojombo/received_events",
    type: "Youtuber/Singer",
    site_admin: false,
  },
  {
    login: "BB ki Vines",
    id: 1,
    node_id: "MDQ6VXNlcjI=",
    avatar_url: "https://mumbaimirror.indiatimes.com/photo/68636207.cms",
    gravatar_id: "",
    url: "https://api.github.com/users/defunkt",
    html_url: "https://github.com/defunkt",
    followers_url: "https://api.github.com/users/defunkt/followers",
    following_url:
      "https://api.github.com/users/defunkt/following{/other_user}",
    gists_url: "https://api.github.com/users/defunkt/gists{/gist_id}",
    starred_url: "https://api.github.com/users/defunkt/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/defunkt/subscriptions",
    organizations_url: "https://api.github.com/users/defunkt/orgs",
    repos_url: "https://api.github.com/users/defunkt/repos",
    events_url: "https://api.github.com/users/defunkt/events{/privacy}",
    received_events_url: "https://api.github.com/users/defunkt/received_events",
    type: "Youtuber/Writer/Actor",
    site_admin: false,
  },
  {
    login: "PewDiePie",
    id: 2,
    node_id: "MDQ6VXNlcjM=",
    avatar_url:
      "https://cached.imagescaler.hbpl.co.uk/resize/scaleWidth/815/cached.offlinehbpl.hbpl.co.uk/news/ORP/pewdiepie_RM_6-8-2019-20190806070709728.jpg",
    gravatar_id: "",
    url: "https://api.github.com/users/pjhyett",
    html_url: "https://github.com/pjhyett",
    followers_url: "https://api.github.com/users/pjhyett/followers",
    following_url:
      "https://api.github.com/users/pjhyett/following{/other_user}",
    gists_url: "https://api.github.com/users/pjhyett/gists{/gist_id}",
    starred_url: "https://api.github.com/users/pjhyett/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/pjhyett/subscriptions",
    organizations_url: "https://api.github.com/users/pjhyett/orgs",
    repos_url: "https://api.github.com/users/pjhyett/repos",
    events_url: "https://api.github.com/users/pjhyett/events{/privacy}",
    received_events_url: "https://api.github.com/users/pjhyett/received_events",
    type: "Youtuber",
    site_admin: false,
  },
  {
    login: "Komal Pandey",
    id: 3,
    node_id: "MDQ6VXNlcjQ=",
    avatar_url:
      "https://yt3.ggpht.com/ytc/AMLnZu9Fx2TUJkUkfmAqTOmOg5HmPRFuWaYHzWoXFYCV0cM=s900-c-k-c0x00ffffff-no-rj",
    gravatar_id: "",
    url: "https://api.github.com/users/wycats",
    html_url: "https://github.com/wycats",
    followers_url: "https://api.github.com/users/wycats/followers",
    following_url: "https://api.github.com/users/wycats/following{/other_user}",
    gists_url: "https://api.github.com/users/wycats/gists{/gist_id}",
    starred_url: "https://api.github.com/users/wycats/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/wycats/subscriptions",
    organizations_url: "https://api.github.com/users/wycats/orgs",
    repos_url: "https://api.github.com/users/wycats/repos",
    events_url: "https://api.github.com/users/wycats/events{/privacy}",
    received_events_url: "https://api.github.com/users/wycats/received_events",
    type: "Digital Content Creator",
    site_admin: false,
  },
  {
    login: "Triggered Insan",
    id: 4,
    node_id: "MDQ6VXNlcjU=",
    avatar_url:
      "https://i.pinimg.com/originals/6e/01/f8/6e01f8dfffb469ffc6cfeb0b6da8718e.jpg",
    gravatar_id: "",
    url: "https://api.github.com/users/ezmobius",
    html_url: "https://github.com/ezmobius",
    followers_url: "https://api.github.com/users/ezmobius/followers",
    following_url:
      "https://api.github.com/users/ezmobius/following{/other_user}",
    gists_url: "https://api.github.com/users/ezmobius/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ezmobius/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ezmobius/subscriptions",
    organizations_url: "https://api.github.com/users/ezmobius/orgs",
    repos_url: "https://api.github.com/users/ezmobius/repos",
    events_url: "https://api.github.com/users/ezmobius/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ezmobius/received_events",
    type: "Youtuber",
    site_admin: false,
  },
  {
    login: "Gaurav Taneja",
    id: 5,
    node_id: "MDQ6VXNlcjY=",
    avatar_url:
      "https://starsunfolded.com/wp-content/uploads/2020/12/Gaurav-Taneja.jpg",
    gravatar_id: "",
    url: "https://api.github.com/users/ivey",
    html_url: "https://github.com/ivey",
    followers_url: "https://api.github.com/users/ivey/followers",
    following_url: "https://api.github.com/users/ivey/following{/other_user}",
    gists_url: "https://api.github.com/users/ivey/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ivey/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ivey/subscriptions",
    organizations_url: "https://api.github.com/users/ivey/orgs",
    repos_url: "https://api.github.com/users/ivey/repos",
    events_url: "https://api.github.com/users/ivey/events{/privacy}",
    received_events_url: "https://api.github.com/users/ivey/received_events",
    type: "Youtuber",
    site_admin: false,
  },
  {
    login: "Aryaki Joon",
    id: 6,
    node_id: "MDQ6VXNlcjc=",
    avatar_url:
      "https://m.timesofindia.com/thumb/88034359.cms?resizemode=4&width=400",
    gravatar_id: "",
    url: "https://api.github.com/users/evanphx",
    html_url: "https://github.com/evanphx",
    followers_url: "https://api.github.com/users/evanphx/followers",
    following_url:
      "https://api.github.com/users/evanphx/following{/other_user}",
    gists_url: "https://api.github.com/users/evanphx/gists{/gist_id}",
    starred_url: "https://api.github.com/users/evanphx/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/evanphx/subscriptions",
    organizations_url: "https://api.github.com/users/evanphx/orgs",
    repos_url: "https://api.github.com/users/evanphx/repos",
    events_url: "https://api.github.com/users/evanphx/events{/privacy}",
    received_events_url: "https://api.github.com/users/evanphx/received_events",
    type: "Youtuber",
    site_admin: false,
  },
  {
    login: "Riya Gogoi",
    id: 7,
    node_id: "MDQ6VXNlcjE3",
    avatar_url:
      "https://shoutingstars.com/wp-content/uploads/2022/07/rW70rz4p_400x400.jpg",
    gravatar_id: "",
    url: "https://api.github.com/users/vanpelt",
    html_url: "https://github.com/vanpelt",
    followers_url: "https://api.github.com/users/vanpelt/followers",
    following_url:
      "https://api.github.com/users/vanpelt/following{/other_user}",
    gists_url: "https://api.github.com/users/vanpelt/gists{/gist_id}",
    starred_url: "https://api.github.com/users/vanpelt/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/vanpelt/subscriptions",
    organizations_url: "https://api.github.com/users/vanpelt/orgs",
    repos_url: "https://api.github.com/users/vanpelt/repos",
    events_url: "https://api.github.com/users/vanpelt/events{/privacy}",
    received_events_url: "https://api.github.com/users/vanpelt/received_events",
    type: "Digital Content Creater",
    site_admin: false,
  },
  {
    login: "Prajakta Koli",
    id: 8,
    node_id: "MDQ6VXNlcjIx",
    avatar_url:
      "https://1.bp.blogspot.com/-MvPKP7gw7bw/YMn8zdH36SI/AAAAAAAAGgs/r-OfcMQO3DkZxpveuE2ww9weCeTsQgr1ACLcBGAsYHQ/s828/Prajakta%2BKoli%2B3.jpg",
    gravatar_id: "",
    url: "https://api.github.com/users/technoweenie",
    html_url: "https://github.com/technoweenie",
    followers_url: "https://api.github.com/users/technoweenie/followers",
    following_url:
      "https://api.github.com/users/technoweenie/following{/other_user}",
    gists_url: "https://api.github.com/users/technoweenie/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/technoweenie/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/technoweenie/subscriptions",
    organizations_url: "https://api.github.com/users/technoweenie/orgs",
    repos_url: "https://api.github.com/users/technoweenie/repos",
    events_url: "https://api.github.com/users/technoweenie/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/technoweenie/received_events",
    type: "Youtuber/Actor",
    site_admin: false,
  },
];

export default Cardsdata;
